apiVersion: v1
kind: Service
metadata:
  name: redisserver
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: app-id-app-session
spec:
  selector:
    app: app-id-app-session
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-id-app-session
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-id-app-session
  template:
    metadata:
      labels:
        app: app-id-app-session
    spec:
      containers:
      - name: app-id-app-session
        image: yourname/app-id-app-session
        env:
        - name: REGION
          value: ""
        - name: TENANT_ID
          value: ""
        - name: APIKEY
          value: ""
        - name: SECRET
          value: ""
        - name: CLIENT_ID
          value: ""
        - name: REDIRECT_URI
          value: "http://localhost:8080/appid/callback"
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hostname
spec:
  tls:
  - hosts:
    - hostname
    secretName: hostname
  rules:
  - host: hostname
    http:
      paths:
      - path: /
        backend:
          serviceName: app-id-app-session
          servicePort: 8080
