apiVersion: v1
kind: Service
metadata:
  name: app-id-app-session
spec:
  selector:
    app: app-id-app-session
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-id-app-session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-id-app-session
  template:
    metadata:
      labels:
        app: app-id-app-session
    spec:
      containers:
      - name: app-id-app-session
        image: yourname/app-id-app-session
        ports:
        - containerPort: 8080
